### ISSUE TITLE
Registration based on namespace 

### ISSUE THREAD

**Issue by dicko2** [agoda-com/Agoda.IoC#18]
It's a pattern we found in some of the systems using autofac 

Inside a project there is a namespace Services, and one for Repositories. All of there are registered the same way (usually singletons) from a method that scan the types only from these namespaces then attributes are used to register them differently. 

The downside I can see here is that the user doesn't always know what the registration of the class is from looking at it. 

The upside is in the example project they have removed a lot of boiler plate code. 

The implementation of we did it would look something like this 

```csharp​
builder.AutoWireNamespace("MyApp.Repositories"), RegisterSingleton)​;
builder.AutoWireNamespace("MyApp.Services"), RegisterScoped)​;
```

Or​you could even do a namespace that maps to an entire project. 

It​ would only register services

- without the registration attribute
- with a single interface they inherit from

**Comment by kchinburarat** [comment]
I have one question what gonna happen if a particular service  implement more than I interface

**Comment by dicko2** [comment]
@kchinburarat ignored, we only register classes with single interface, for multiple you need to add attribute

This is what i dont like about the solution, there's a lot of magic that is behind the scenes, by adding a new interface you can break DI silently

**Comment by dicko2** [comment]
https://autofac.readthedocs.io/en/latest/register/scanning.html#specifying-services

Actually if we mimic the behavior of the original autofac implementation we want to replace should register as all interfaces for AsImplementedInterfaces

**Comment by szaboopeeter** [comment]
For projects that have a well-defined enough structure (in the sense of what you described above) that they can use this approach, why not just use autofac instead, if it already provides a way to achieve what we're looking for? :) I feel like if I can come up with a consistent naming pattern where the namespace or class name can define the DI scope, then I would want to go all-in with that, rather than mix it with attribute-based registration.

I'm not saying that it's a bad idea to have this functionality here, but we might want to re-think the problem statement of this library if we start to move certain ways of registration back to config files.

**Comment by dicko2** [comment]
I tend to agree with @szaboopeeter 

Personally i think its a bit of an anti pattern, because it takes visibility away from the engineers.

In the example of the extranet we have that was using this, the default was at some point changed to transient, i'm sure that some one was just in a hurry and trying to "make it work" and didn't understand what they were doing, then it was missed in a large code review, the terminology in autofac isn't straight forward at times, so i can understand.

Good news is we have some cleaning up to do on 3k classes on that extranet to save a lot of CPU and RAM by moving things to singletons and per request :)

So I think I'll close this with the reasoning.

Magic isn't always good, it's better to add a bit of boiler plate code sometimes to make the code easier to understand for people, and also so people's intentions are explicit in the code they write. i.e. you cant register a class in DI without adding an attribute that says "This is a singleton" in plain English.
