### ISSUE TITLE
Add support  for RegisterHostedServiceAttribute in Source Generator to register HostedService to IoC

### ISSUE THREAD

**Issue by kchinburarat** [agoda-com/Agoda.IoC#29]
# Feature request

## Type

- [x] - Enhancement - completely new feature
- [ ] - Improvement - make what we have better

## Is your feature request related to a problem?
No
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## Describe the solution you'd like
I need to introduce a new attribute named RegisterHostedService to allow consumers to register the HostedService service using this attribute.

For example i have `TimedHostedService ` like 

```csharp
[RegisterHostedService]
public class TimedHostedService : IHostedService, IDisposable
{
    private int executionCount = 0;
    private readonly ILogger<TimedHostedService> _logger;
    private Timer? _timer = null;

    public TimedHostedService(ILogger<TimedHostedService> logger)
    {
        _logger = logger;
    }

    public Task StartAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation("Timed Hosted Service running.");

        _timer = new Timer(DoWork, null, TimeSpan.Zero,
            TimeSpan.FromSeconds(5));

        return Task.CompletedTask;
    }

    private void DoWork(object? state)
    {
        var count = Interlocked.Increment(ref executionCount);

        _logger.LogInformation(
            "Timed Hosted Service is working. Count: {Count}", count);
    }

    public Task StopAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation("Timed Hosted Service is stopping.");

        _timer?.Change(Timeout.Infinite, 0);

        return Task.CompletedTask;
    }

    public void Dispose()
    {
        _timer?.Dispose();
    }
}
```
then our Source Generator will  produce this code

```csharp
services.AddHostedService<TimedHostedService>();
```

## Additional context
> Add any other context or screenshots about the feature request here.

**Comment by kchinburarat** [comment]
@szaboopeeter @dicko2 
What do you think?? :)

**Comment by szaboopeeter** [comment]
Sounds like a reasonable feature to add :)

You mentioned source generator in your description - there's nothing blocking this from being implemented with the reflection approach as well (I mean: both approaches), right?

**Comment by kchinburarat** [comment]
@szaboopeeter I believe we can implement on both

**Comment by kchinburarat** [comment]
I have added this feature to source generator.  :)
